---
title: "Covid91 vaccine study Final2022"
author: "DESMOND KOUTSO"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="final_Data.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
```

# Introduction

A new  preventative vaccine (covid91) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

### Null and Alternative hypothesis

$H_O$: There is no difference between how effective the vaccine is for any of the sub-groups that uses it. These two variables are independent.  

$H_A$: There is a difference between how effective the vaccine is for any of the subgroup that uses it. These two variables are dependent.  

### Methods

This data set is a CAT~CAT since both variables are categorical. Whether the vaccine is effective or not can be categorized and also, the subgroups can be categorized. A barchat will be used to describe the graphical results, a data table for the numerical results, a chi-squared test and fisher exact test to describe the inferential results for the different 4 subgroups. To end I will give my recommendation on whether or not each sub-group should take the vaccine.   

## Males

### Graphical Descriptive results

### Numerical Descriptive results

### Inferential Resuslts

### Male Conclusion


## Females

### Graphical Descriptive Results

### Numerical Descriptive Results

### Inferential results

### Females Conclusion

## LGBTQ

### Graphical Descriptive Results

### Numerical Descriptive Results

### Inferential results

### LGBTQ Conclusion


## Druggies

### Graphical Descriptive Results

### Numerical Descriptive Results

### Inferential results

### Druggies Conclusion

## Final Conclusion
